# SPDX-FileCopyrightText: 2023 - 2024 Nikita Chernyi
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Prometheus blackbox exporter paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ prometheus_blackbox_exporter_uid }}"
    group: "{{ prometheus_blackbox_exporter_gid }}"
  with_items:
    - "{{ prometheus_blackbox_exporter_base_path }}"
    - "{{ prometheus_blackbox_exporter_config_path }}"

- name: Ensure Prometheus blackbox exporter labels file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ prometheus_blackbox_exporter_config_path }}/labels"
    owner: "{{ prometheus_blackbox_exporter_uid }}"
    group: "{{ prometheus_blackbox_exporter_gid }}"
    mode: "0640"

- name: Ensure Prometheus blackbox exporter configuration file installed
  ansible.builtin.copy:
    content: "{{ prometheus_blackbox_exporter_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ prometheus_blackbox_exporter_config_path }}/config.yml"
    owner: "{{ prometheus_blackbox_exporter_uid }}"
    group: "{{ prometheus_blackbox_exporter_gid }}"
    mode: "0640"

- name: Ensure Prometheus blackbox exporter container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ prometheus_blackbox_exporter_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ prometheus_blackbox_exporter_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else prometheus_blackbox_exporter_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Prometheus blackbox exporter container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ prometheus_blackbox_exporter_container_image }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure Prometheus blackbox exporter container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ prometheus_blackbox_exporter_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  when: prometheus_blackbox_exporter_container_network != 'host'

- name: Ensure Prometheus blackbox exporter container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ prometheus_blackbox_exporter_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure Prometheus blackbox exporter systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/prometheus-blackbox-exporter.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ prometheus_blackbox_exporter_identifier }}.service"
    mode: "0644"
