---

- name: Ensure prometheus-blackbox-exporter is installed
  tags:
    - setup-all
    - setup-prometheus
    - setup-prometheus-blackbox-exporter
    - install-all
    - install-prometheus
    - install-prometheus-blackbox-exporter
  block:
    - name: Include prometheus-blackbox-exporter config validation tasks
      when: prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Include prometheus-blackbox-exporter installation tasks
      when: prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Ensure prometheus-blackbox-exporter is removed
  tags:
    - setup-all
    - setup-prometheus
    - setup-prometheus-blackbox-exporter
    - install-all
    - install-prometheus
    - install-prometheus-blackbox-exporter
  block:
    - name: Include prometheus-blackbox-exporter removal tasks
      when: not prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
