# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Prometheus blackbox exporter installation tasks
  when: prometheus_blackbox_exporter_enabled | bool
  tags:
    - setup-all
    - setup-prometheus-blackbox-exporter
    - install-all
    - install-prometheus-blackbox-exporter
  block:
    - name: Validate Prometheus blackbox exporter configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Prometheus blackbox exporter
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Prometheus blackbox exporter uninstallation tasks
  when: not prometheus_blackbox_exporter_enabled | bool
  tags:
    - setup-all
    - setup-prometheus-blackbox-exporter
  block:
    - name: Uninstall Prometheus blackbox exporter
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
