# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure prometheus-blackbox-exporter is installed
  block:
    - name: Include prometheus-blackbox-exporter config validation tasks
      when: prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Include prometheus-blackbox-exporter installation tasks
      when: prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-prometheus-blackbox-exporter
    - install-all
    - install-prometheus-blackbox-exporter

- name: Ensure prometheus-blackbox-exporter is removed
  block:
    - name: Include prometheus-blackbox-exporter removal tasks
      when: not prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-prometheus-blackbox-exporter
