# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform prometheus-blackbox-exporter installation tasks
  tags:
    - setup-all
    - setup-prometheus-blackbox-exporter
    - install-all
    - install-prometheus-blackbox-exporter
  block:
    - name: Validate prometheus-blackbox-exporter configuration
      when: prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install prometheus-blackbox-exporter
      when: prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform prometheus-blackbox-exporter uninstallation tasks
  tags:
    - setup-all
    - setup-prometheus-blackbox-exporter
  block:
    - name: Uninstall prometheus-blackbox-exporter
      when: not prometheus_blackbox_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
